import { Knex } from "knex";
import { ETableNames } from "../ETableNames";

export const seed = async (Knex: Knex) => {

  const [{ count }] = await Knex(ETableNames.cidade).count<[{ count: number }]>('* as count')
  if (!Number.isInteger(count) || Number(count) > 0) return;

  // const cidadesToInsert = cidadesToWorld.map(nomeCidade => ({nome: nomeCidade}));

  const cidadesToInsert = cidadesToWorld
  await Knex(ETableNames.cidade).insert(cidadesToInsert);

}

const cidadesToWorld = [
  { "nome": "Paris" },
  { "nome": "Londres" },
  { "nome": "Nova York" },
  { "nome": "Tóquio" },
  { "nome": "Rio de Janeiro" },
  { "nome": "Barcelona" },
  { "nome": "Roma" },
  { "nome": "Dubai" },
  { "nome": "Cidade do Cabo" },
  { "nome": "Sydney" },
  { "nome": "Vancouver" },
  { "nome": "Hong Kong" },
  { "nome": "Cingapura" },
  { "nome": "Istambul" },
  { "nome": "Amsterdã" },
  { "nome": "San Francisco" },
  { "nome": "Los Angeles" },
  { "nome": "Buenos Aires" },
  { "nome": "Lisboa" },
  { "nome": "Praga" },
  { "nome": "Viena" },
  { "nome": "Florença" },
  { "nome": "Bangcoc" },
  { "nome": "Berlim" },
  { "nome": "Quioto" },
  { "nome": "Seul" },
  { "nome": "Chicago" },
  { "nome": "Las Vegas" },
  { "nome": "Munique" },
  { "nome": "Cidade do México" },
  { "nome": "Atenas" },
  { "nome": "Edimburgo" },
  { "nome": "Kuala Lumpur" },
  { "nome": "Lima" },
  { "nome": "Havana" },
  { "nome": "Cracóvia" },
  { "nome": "San Petersburgo" },
  { "nome": "Marraquexe" },
  { "nome": "Doha" },
  { "nome": "Auckland" },
  { "nome": "Helsinque" },
  { "nome": "Reykjavik" },
  { "nome": "Bruxelas" },
  { "nome": "Tel Aviv" },
  { "nome": "Dubrovnik" },
  { "nome": "Cidade de Quebec" },
  { "nome": "Cartagena" },
  { "nome": "Jerusalém" },
  { "nome": "Osaka" },
  { "nome": "Toronto" },
  { "nome": "Montreal" },
  { "nome": "Orlando" },
  { "nome": "Miami" },
  { "nome": "São Paulo" },
  { "nome": "Brasília" },
  { "nome": "Salvador" },
  { "nome": "Recife" },
  { "nome": "Fortaleza" },
  { "nome": "Porto Alegre" },
  { "nome": "Curitiba" },
  { "nome": "Belo Horizonte" },
  { "nome": "Cairo" },
  { "nome": "Nairobi" },
  { "nome": "Lagos" },
  { "nome": "Casablanca" },
  { "nome": "Accra" },
  { "nome": "Túnis" },
  { "nome": "Almaty" },
  { "nome": "Islamabad" },
  { "nome": "Nova Délhi" },
  { "nome": "Mumbai" },
  { "nome": "Goa" },
  { "nome": "Jaipur" },
  { "nome": "Kathmandu" },
  { "nome": "Hanoi" },
  { "nome": "Ho Chi Minh" },
  { "nome": "Manila" },
  { "nome": "Taipei" },
  { "nome": "Macau" },
  { "nome": "Xangai" },
  { "nome": "Pequim" },
  { "nome": "Chengdu" },
  { "nome": "Busan" },
  { "nome": "Jeju" },
  { "nome": "Sapporo" },
  { "nome": "Osaka" },
  { "nome": "Nara" },
  { "nome": "Hiroshima" },
  { "nome": "Melbourne" },
  { "nome": "Perth" },
  { "nome": "Brisbane" },
  { "nome": "Adelaide" },
  { "nome": "Queenstown" },
  { "nome": "Wellington" },
  { "nome": "Christchurch" },
  { "nome": "Atenas" },
  { "nome": "Mykonos" },
  { "nome": "Santorini" },
  { "nome": "Nice" },
  { "nome": "Lyon" },
  { "nome": "Marselha" },
  { "nome": "Bordeaux" },
  { "nome": "Toulouse" },
  { "nome": "Milão" },
  { "nome": "Veneza" },
  { "nome": "Verona" },
  { "nome": "Nápoles" },
  { "nome": "Bolonha" },
  { "nome": "Madri" },
  { "nome": "Sevilha" },
  { "nome": "Granada" },
  { "nome": "Bilbau" },
  { "nome": "Valência" },
  { "nome": "Porto" },
  { "nome": "Coimbra" },
  { "nome": "Funchal" },
  { "nome": "Évora" },
  { "nome": "Genebra" },
  { "nome": "Zurique" },
  { "nome": "Lucerna" },
  { "nome": "Interlaken" },
  { "nome": "Munique" },
  { "nome": "Hamburgo" },
  { "nome": "Colônia" },
  { "nome": "Frankfurt" },
  { "nome": "Stuttgart" },
  { "nome": "Oslo" },
  { "nome": "Bergen" },
  { "nome": "Estocolmo" },
  { "nome": "Gotemburgo" },
  { "nome": "Copenhague" },
  { "nome": "Malmo" },
  { "nome": "Varsóvia" },
  { "nome": "Gdansk" },
  { "nome": "Wroclaw" },
  { "nome": "Bratislava" },
  { "nome": "Ljubljana" },
  { "nome": "Budapeste" },
  { "nome": "Zagreb" },
  { "nome": "Sarajevo" },
  { "nome": "Belgrado" },
  { "nome": "Bucareste" },
  { "nome": "Sofia" },
  { "nome": "Vilnius" },
  { "nome": "Riga" },
  { "nome": "Tallinn" },
  { "nome": "Dublin" },
  { "nome": "Galway" },
  { "nome": "Cork" },
  { "nome": "Belfast" },
  { "nome": "Luxemburgo" }
];

